#:kivy 2.3.1
<MyScreenManager>:
    dispatcher: app.ev
    LoginScreen:
    CheckoutScreen:

<LoginScreen>:
    name: "LoginScreen"
    GreetLabel:
        text: "Chip her!"
        font_size: "24sp"
        dispatcher: app.ev




<CheckoutScreen>:
    name: "CheckoutScreen"
    dispatcher: app.ev
    BoxLayout:
        orientation: "vertical"
        UserInfoLayout:
        ItemScrollView:
            dispatcher: app.ev

        
